feat(security): implement Spring Security with JWT decoding and role …
maydek1/cab-aggregator-app pull request #9
Opened 2024-11-11 07:33 UTC by maydek1

…parsing

- Configured Spring Security for authentication and authorization
- Added JWT token decoding and implemented role parsing from JWT claims
- Set up role-based access control for secured endpoints
- Improved security by enforcing authorization checks based on user roles

2024-11-11 22:38 UTC, Naza1re requested changes

2024-11-11 22:38 UTC, Naza1re commented on car-station-service/src/main/java/com/software/modsen/carstationservice/controller/CarController.java
Попробуй вынести всю логику связанную с свагером в интрефейсы, и унаследуй этот класс от этого интерфейса

2024-11-17 21:05 UTC, maydek1 commented on car-station-service/src/main/java/com/software/modsen/carstationservice/controller/CarController.java
Вынес

2024-11-18 12:23 UTC, Naza1re approved these changes

2024-11-18 12:24 UTC, merged